blank_issues_enabled: true
contact_links:
  - name: Apex Vibes Support
    url: https://t.me/ApexVibesSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Apex Vibes.tech/
    about: Documentation for getting started with bot.
